baseurl = "https://www.akonobrathwaite.com"
title = "Akono Brathwaite"
theme = ["coder-portfolio-edited", "coder-portfolio"]
languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname"

[params]
    author = "Akono Brathwaite"
    description = "Akono's personal website and blog"
    keywords = "blog,developer,personal"
    info = "Web Developer"
    avatarurl = "images/me.jpg"
    # footercontent = "Enter a text here."

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = true

    rtl = false

    # snsShare = true # share button to bottom of page

    thumbnail = "images/tn.png" # default sns thumbnail

    # Custom CSS
    custom_css = []

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/wingraptor/"
# [[params.social]]
#     name = "Gitlab"
#     icon = "fab fa-gitlab"
#     weight = 2
#     url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "Twitter"
    weight = 3
    url = "https://twitter.com/akonobrath/"
[[params.social]]
    name = "LinkedIn"
    weight = 4
    url = "https://www.linkedin.com/in/akono-brathwaite-a0446297/"
# [[params.social]]
#     name = "Medium"
#     icon = "fab fa-medium"
#     weight = 5
#     url = "https://medium.com/@johndoe"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"
# [[menu.main]]
#     name = "Contact me"
#     weight = 5
#     url = "/contact/"